# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Myths的个人博客
subtitle: 闻道有先后，术业有专攻
description: 这里是Myths的个人博客，记录着自己在技术之路上成长的点点滴滴，希望能用自己的努力来帮助身边的朋友。
author: Myths
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.mythsman.com
root: /
permalink: :year/:month/:day/:id/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
 - README.md
 - CNAME

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 50
pagination_dir: page


#hexo-generator-index
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia


#hexo-deployer-git
deploy:
  type: git
  repository: git@github.com:mythsman/mythsman.github.io.git
  branch: master
  message: update my blog.

#hexo-generator-json-content
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

#hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content: true


#hexo-generator-sitemap
sitemap:
  path: sitemap.xml

#hexo-douban
douban:
  user: mythsman
  book:
    title: 我的阅读
    quote: 写了个<a href="https://github.com/mythsman/hexo-douban" target="_blank">插件</a>记录我读的书。
  movie:
    title: 我的电影
    quote: 写了个<a href="https://github.com/mythsman/hexo-douban" target="_blank">插件</a>记录我看的电影。
  game:
    title: 我的游戏
    quote: 写了个<a href="https://github.com/mythsman/hexo-douban" target="_blank">插件</a>记录我沉迷的游戏。
  timeout: 100000

#hexo-generator-tag
tag_generator:
  per_page: 0

#hexo-generator-category
category_generator:
  per_page: 0

#hexo-generator-archive
archive_generator:
  per_page: 50
  yearly: true
  monthly: true
  daily: false

#hexo-excerpt
excerpt_depth: 5

marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: false


#hexo-filter-asciinema
asciinema:
  enable: true
